name: CI MRQ

#Cuando se dispara el evento que ejecuta el workflow
on:
  push:
    branches:
      - main
jobs:  
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php-version: [8.1, 8.2, 8.3]
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - run: composer install
      - run: ./vendor/bin/phpunit --log-junit resultats.xml
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: resultats-MRQ-${{ matrix.php-version }}
          path: resultats.xml
      
