name: CI MRQ

#Cuando se dispara el evento que ejecuta el workflow
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Descarregar codi repositori
      - uses: actions/checkout@v4
      # Preparar PHP 8.2 al runner
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 'PHP 8.2'
      - run: composer install
      - run: ./vendor/bin/phpuniT
      
